import InfoPage from "@/components/InfoPage";
import Link from "next/link";
import { pageMetadata } from "@/lib/seo";
export const metadata = pageMetadata("Política editorial e correções", "Como o Capilarmente identifica autoria, verifica fontes, corrige conteúdo e distingue comparação editorial de publicidade.", "/editorial");
export default function Page() { return <InfoPage title="Política editorial" intro="Como produzimos, verificamos e corrigimos o conteúdo do Capilarmente.">
<p>Atualizada em 9 de setembro de 2026.</p>
<h2>Autoria e inteligência artificial</h2><p>Os artigos são assinados pela Redação Capilarmente, com apoio de ferramentas de inteligência artificial. Não apresentamos personas como profissionais reais e não declaramos revisão médica sem um profissional identificado, credenciais verificadas e revisão documentada daquele conteúdo.</p>
<h2>Fontes e limites da evidência</h2><p>Priorizamos documentos de órgãos públicos, diretrizes de sociedades profissionais e estudos originais. Uma referência precisa corresponder ao título, aos autores e à afirmação que pretende sustentar. A existência de um DOI, sozinha, não comprova uma alegação.</p><p>Diferenciamos resultados de estudos, hipóteses e incertezas. Não transformamos resultados de um pequeno estudo em promessa de resultado individual. Conteúdo mais antigo está passando por conferência editorial; não afirmamos que todo o acervo recebeu revisão clínica independente.</p>
<h2>Correções e datas</h2><p>Erros de fontes, autoria, segurança ou interpretação devem ser corrigidos no texto. Alterações relevantes recebem data e nota de correção; a data original de publicação é preservada. Ajustes visuais não são motivo para apresentar um artigo como recém-revisado.</p><p>Em setembro de 2026, retiramos credenciais profissionais sem comprovação e alegações de revisão médica, além de substituir os cálculos diagnósticos do questionário por um resumo educativo.</p><p>Para apontar uma incorreção, envie a URL, o trecho e uma fonte que permita conferir o problema pelo nosso <Link href="/contato">canal de contato</Link>. Não envie prontuários, exames ou outros dados de saúde.</p>
<h2>Produtos, preços e comissões</h2><p>Comparações documentais se baseiam nas características publicadas, composição, quantidade e custo por unidade. Testes práticos só serão declarados quando realmente realizados, com método e limitações informados. Não compramos avaliações nem inventamos depoimentos.</p><p>Preços são uma fotografia da fonte e da data indicadas, sujeitos a frete, região, estoque e alterações. Ofertas com comissão terão a indicação “Link de afiliado” próxima ao botão e não determinarão as conclusões sobre eficácia ou segurança.</p>
<h2>Questionário educativo</h2><p>O roteiro gratuito organiza respostas para uma consulta. Não calcula probabilidades de doenças, gravidade clínica ou indicação de medicamentos. As respostas ficam no navegador durante a sessão e não são enviadas para análise ou publicidade. A <Link href="/privacidade">política de privacidade</Link> descreve o armazenamento e as métricas de navegação.</p>
</InfoPage>; }
