"use client";
import { useRef, useState } from "react";
import { calculateCosts } from "@/lib/costs";
import { recordEvent } from "@/lib/analytics";
const currency = (n: number) => n.toLocaleString("pt-BR", {style:"currency", currency:"BRL"});
const fields = [{key:"monthly", label:"Cuidados mensais (R$)", hint:"Some apenas os itens do seu planejamento."}, {key:"consultation", label:"Preço de cada consulta (R$)", hint:"Use um orçamento recebido."}, {key:"visits", label:"Consultas previstas em 12 meses", hint:"Quantidade definida no seu planejamento."}, {key:"procedure", label:"Procedimento ou compra única (R$)", hint:"Inclua somente se fizer parte do seu orçamento."}] as const;
export default function CostCalculator() {
 const [form, setForm] = useState({monthly:"", consultation:"", visits:"", procedure:""});
 const [result, setResult] = useState<ReturnType<typeof calculateCosts> | null>(null);
 const [error, setError] = useState(""); const tracked = useRef(false);
 return <section id="calculadora" aria-labelledby="titulo-calculadora" className="my-10 rounded-2xl border border-forest-200 bg-sage-50 p-5 sm:p-8"><h2 id="titulo-calculadora" className="text-2xl font-display mb-3">Calcule seu orçamento de 12 meses</h2><p className="mb-6">Preencha com preços que você encontrou. Campos vazios contam como zero; o resultado não é uma recomendação de tratamento. Os valores ficam no seu navegador.</p><form onSubmit={event => {event.preventDefault(); try { if (Object.values(form).every(v => v === "")) throw new Error("Preencha pelo menos um custo para calcular."); if (Number(form.consultation) > 0 && !form.visits) throw new Error("Informe a quantidade de consultas para incluir esse custo."); setResult(calculateCosts({monthly:Number(form.monthly), consultation:Number(form.consultation), visits:Number(form.visits), procedure:Number(form.procedure)})); setError(""); if (!tracked.current) {recordEvent("calculator_use");tracked.current=true;} } catch(e) {setResult(null); setError((e as Error).message);} }}><div className="grid sm:grid-cols-2 gap-5">{fields.map(field => <div key={field.key}><label className="block font-semibold mb-2" htmlFor={`cost-${field.key}`}>{field.label}</label><input id={`cost-${field.key}`} aria-describedby={`hint-${field.key}`} className="w-full p-3 rounded-lg border border-warm-300 bg-white" type="number" min="0" max={field.key === "visits" ? "1000" : "10000000"} step={field.key === "visits" ? "1" : "0.01"} inputMode={field.key === "visits" ? "numeric" : "decimal"} value={form[field.key]} onChange={e => {setForm({...form, [field.key]:e.target.value});setResult(null);}} /><p className="text-sm mt-1" id={`hint-${field.key}`}>{field.hint}</p></div>)}</div><div className="flex flex-wrap gap-3 mt-6"><button className="btn-primary" type="submit">Calcular orçamento</button><button className="btn-secondary" type="button" onClick={() => {setForm({monthly:"", consultation:"", visits:"", procedure:""});setResult(null);setError("");}}>Limpar valores</button></div></form>{error && <p className="mt-4" role="alert">{error}</p>}<div aria-live="polite">{result && <div className="mt-6 border-t border-forest-200 pt-6"><dl className="grid gap-4 sm:grid-cols-3"><div><dt>Total em 12 meses</dt><dd className="text-2xl font-bold text-forest-800">{currency(result.firstYear)}</dd></div><div><dt>Equivalente por mês</dt><dd className="text-xl font-bold">{currency(result.monthlyEquivalent)}</dd></div><div><dt>Sem a compra única</dt><dd className="text-xl font-bold">{currency(result.recurringAnnual)} / ano</dd></div></dl><p className="text-sm mt-4">O equivalente mensal divide o total por 12; não representa uma oferta de parcelamento. Some frete, manutenção e outras despesas aos campos correspondentes. Valores futuros podem mudar.</p></div>}</div></section>;
}
